Repository Team-TIFY/TIFY-CLIENT, pull requests merged in 2023-12, with the labels that each got.

#186 refac: 선물하기페이지 수정
  src/components/atoms/BottomSheet/index.tsx
  src/components/friends/PresentRecommend.tsx
  src/pages/weekly/WeeklyMainQuestion.tsx
  src/utils/apis/friends/FriendsApi.tsx
Labels: Refactor

#191 [Feat]: 신고하기 기능 추가
  src/components/WeeklyQuestion/Answer/AnswerList.tsx
  src/components/WeeklyQuestion/Answer/DailyAnswerListContainer.tsx
  src/components/atoms/Input/ShortInput/index.tsx
  src/components/atoms/Navigationbar/index.tsx
  src/components/atoms/TextBubble/index.tsx
  src/components/friends/PresentRecommend.tsx
  src/components/funnel/MultiAnswerStep.tsx
  src/components/funnel/OneAnswerStep.tsx
  src/components/profile/UserTagDataListItem.tsx
  src/pages/weekly/CheckAllAnswers.tsx
  src/utils/apis/weekly/WeeklyApi.ts
  src/utils/apis/weekly/questionType.ts
  src/utils/getNotAnswerFriends.ts
Labels: Feature

#193 [Feat]: 말풍선 애니메이션 처리, 배경 블러 처리, 신고하기 API 연결
  src/components/WeeklyQuestion/Answer/DailyAnswerListContainer.tsx
  src/components/atoms/TextBubble/index.tsx
  src/components/atoms/TodayCategory/TodayCategory.stories.tsx
  src/components/atoms/TodayList/TodayList.stories.tsx
  src/components/layouts/Dimmer.tsx
  src/styles/theme/global.ts
  src/utils/apis/weekly/WeeklyApi.ts
  src/utils/apis/weekly/questionType.ts
Labels: Feature

#195 [Fix]: Dockerfile 쓸데없는 주석 제거
  dockerfile
Labels: Bug

#197 [Fix]: 빌드 에러 발생 수정
  src/components/atoms/TodayList/TodayList.stories.tsx
Labels: Bug

#199 [Feat]: 데일리 질문 비디오 애니메이션 추가, 3D 에셋 톤 재조정
  dockerfile
  public/images/drum.png
  public/images/food.png
  public/images/passport.png
  public/videos/drink.mp4
  public/videos/drum.mp4
  public/videos/food.mp4
  public/videos/music.mp4
  public/videos/my.mp4
  public/videos/passport.mp4
  public/videos/relation.mp4
  src/components/WeeklyQuestion/Answer/DailyAnswerListContainer.tsx
  src/components/WeeklyQuestion/VideoBox.tsx
  src/pages/weekly/AnswerDailyQuestion.tsx
  src/utils/apis/friends/FriendsType.ts
  src/utils/apis/weekly/questionType.ts
Labels: Feature

#202 [Feat]: 유저 콕 찌르기 기능 개발
  src/components/WeeklyQuestion/poke/PokeList.tsx
  src/components/atoms/BottomSheet/index.tsx
  src/libs/hooks/index.ts
  src/libs/hooks/useBottomSheet.tsx
  src/libs/hooks/useQuestionMutate.ts
  src/pages/weekly/CheckAllAnswers.tsx
  src/utils/apis/friends/FriendsApi.tsx
  src/utils/apis/friends/FriendsType.ts
Labels: Feature

#211 [Feature] 취향 상자 수정 api 연결
  index.html
  src/libs/store/onboard.ts
  src/pages/onboarding/details/selectInfo/SelectFavor.tsx
  src/pages/profile/EditFavorBox.tsx
  src/utils/apis/user/UserApi.ts
  src/utils/parseFavorBox.ts
  src/utils/tasteBoxImage.ts
Labels: Feature

#212 [Refac] 선물하기, 온보딩, 설정 수정
  index.html
  src/assets/icons/Vector.tsx
  src/components/atoms/BottomSheet/index.tsx
  src/components/atoms/Input/ShortInput/index.tsx
  src/components/friends/PresentRecommend.tsx
  src/components/friends/bottomsheet/PriceFilter.tsx
  src/components/friends/bottomsheet/SortItem.tsx
  src/libs/store/onboard.ts
  src/libs/store/present.ts
  src/pages/onboarding/details/Agreement.tsx
  src/pages/onboarding/details/SignUp.tsx
  src/pages/onboarding/details/selectInfo/SelectFavor.tsx
  src/pages/onboarding/details/signup/Birth.tsx
  src/pages/onboarding/details/signup/Gender.tsx
  src/pages/onboarding/details/signup/Name.tsx
  src/pages/onboarding/details/signup/StartMent.tsx
  src/pages/onboarding/details/signup/UserId.tsx
  src/pages/onboarding/index.tsx
  src/pages/settingPage/Account.tsx
  src/pages/settingPage/WriteForCustomer.tsx
  src/styles/theme/typo.ts
  src/utils/apis/setting.ts
Labels: Refactor

#220 [Fix]: 패키징 전 빌드 에러 해결
  index.html
  src/components/atoms/Category/Category.stories.tsx
  src/components/atoms/Tag/Tag.stories.ts
  src/utils/subCategoryTitle.ts
Labels: Bug

#219 [Fix]: 투데이 관련 3차 QA 반영사항 반영
  index.html
  src/components/WeeklyQuestion/Answer/DailyAnswerListContainer.tsx
  src/components/WeeklyQuestion/DailyQuestionBox.tsx
  src/components/WeeklyQuestion/poke/PokeList.tsx
  src/components/atoms/ProfileBox/index.tsx
  src/pages/onboarding/details/selectInfo/SelectFavor.tsx
  src/pages/profile/EditFavorBox.tsx
  src/pages/profile/index.tsx
  src/pages/weekly/AnswerDailyQuestion.tsx
  src/pages/weekly/CheckAllAnswers.tsx
  src/pages/weekly/WeeklyMainQuestion.tsx
  src/utils/apis/user/UserApi.ts
Labels: Refactor

#228 [Feat] : 애플 로그인 구현
  index.html
  src/App.tsx
  src/components/auth/RequireAuth.tsx
  src/libs/hooks/useAuthMutate.ts
  src/libs/hooks/useRefresh.ts
  src/libs/store/auth.ts
  src/pages/home/Login.tsx
  src/pages/home/Redirect/AppleRedirect.tsx
  src/pages/home/Redirect/KaKaoRedirect.tsx
  src/utils/apis/auth/AuthApi.ts
  src/utils/apis/auth/AuthType.ts
Labels: Feature

#235 [Fix] : 3차 QA 반영
  index.html
  public/images/giftBox.png
  src/App.tsx
  src/components/WeeklyQuestion/Answer/DailyAnswerListContainer.tsx
  src/components/WeeklyQuestion/CheckTodayDate.tsx
  src/components/WeeklyQuestion/DailyQuestionBox.tsx
  src/components/WeeklyQuestion/VideoBox.tsx
  src/components/atoms/DayWeek/WeekGroup/Week/index.tsx
  src/components/atoms/Navigationbar/index.tsx
  src/components/atoms/SnackBar/index.tsx
  src/components/atoms/TextWithLineBreak/index.tsx
  src/components/auth/RequireAuth.tsx
  src/components/friends/CopyMyIdButton.tsx
  src/components/funnel/MultiAnswerStep.tsx
  src/components/funnel/OneAnswerStep.tsx
  src/components/funnel/SearchAnswerStep.tsx
  src/libs/hooks/useFriendMutate.ts
  src/libs/store/dummy.ts
  src/pages/friends/index.tsx
  src/pages/home/Login.tsx
  src/pages/home/NotFound.tsx
  src/pages/index.tsx
  src/pages/onboarding/details/signup/Birth.tsx
  src/pages/onboarding/index.tsx
  src/pages/profile/index.tsx
  src/pages/settingPage/VersionInfo.tsx
  src/pages/settingPage/index.tsx
  src/pages/weekly/AnswerDailyQuestion.tsx
  src/pages/weekly/WeeklyMainQuestion.tsx
  src/pages/weekly/index.tsx
  src/styles/theme/theme.ts
  src/utils/apis/setting.ts
Labels: Refactor

#239 [Feat] : 메인화면 애니메이션 적용
  index.html
  src/components/WeeklyQuestion/DailyQuestionBox.tsx
  src/components/WeeklyQuestion/QuestionImg.tsx
  src/components/atoms/RoundButton/index.tsx
  src/components/funnel/MultiAnswerStep.tsx
  src/components/funnel/OneAnswerStep.tsx
  src/components/funnel/SearchAnswerStep.tsx
  src/constants/todayList.ts
  src/pages/onboarding/details/HalfSuccess.tsx
  src/pages/weekly/AnswerDailyQuestion.tsx
  src/pages/weekly/CheckAllAnswers.tsx
  src/pages/weekly/WeeklyMainQuestion.tsx
  src/utils/subCategoryTitle.ts
Labels: Feature
