Repository Team-TIFY/TIFY-CLIENT, pull requests merged in 2023-11, with the labels that each got.

#126 [Refac] 프로필 페이지 리팩토링
  src/assets/icons/Gift.tsx
  src/components/atoms/Category/Category.stories.tsx
  src/components/atoms/Category/index.tsx
  src/components/atoms/RoundButton/index.tsx
  src/components/atoms/SquareButton/index.tsx
  src/components/profile/EditProfileImage.tsx
  src/components/profile/NewTasteCategory.tsx
  src/components/profile/NewTasteCategoryList.tsx
  src/components/profile/OnboardingStatus.tsx
  src/components/profile/ProfileButtons.tsx
  src/components/profile/ProfileHeader.tsx
  src/components/profile/ProfileMenuButtons.tsx
  src/components/profile/SubCategoryListItem.tsx
  src/components/profile/UserDetail.tsx
  src/components/profile/UserTagData.tsx
  src/components/profile/UserTagDataListItem.tsx
  src/libs/hooks/useProfileMenuButtonsData.ts
  src/libs/hooks/useSetFriendRecoilState.ts
  src/libs/hooks/useSetProfileRecoilState.ts
  src/libs/store/friend.ts
  src/pages/profile/EditProfile.tsx
  src/pages/profile/EditProfileButton.tsx
  src/pages/profile/EditUserInfo.tsx
  src/pages/profile/NewTaste.tsx
  src/pages/profile/Profile.tsx
  src/pages/profile/index.tsx
  src/utils/apis/user/UserType.ts
  src/utils/subCategoryTitle.ts
Labels: Feature

#130 [Fix] 온보딩 상태 수정 페이지 버그 해결 (처음 접속 시 선택된 버튼 없도록, 불필요한 검색 횟수 감소)
  src/pages/onboarding/details/selectInfo/DetailInfo.tsx
  src/pages/profile/Profile.tsx
Labels: Performance

#146 [feat] 선물하기 페이지 뷰 생성 및 설정 페이지 기능 부분추가
  .pnp.cjs
  .yarn/cache/@types-react-copy-to-clipboard-npm-5.0.7-cf9459d351-adc2970c87.zip
  package.json
  src/assets/icons/Delete.tsx
  src/assets/icons/FileIcon.tsx
  src/assets/icons/FilterIcon.tsx
  src/assets/icons/ItemFilter.tsx
  src/assets/icons/PriceFilter.tsx
  src/assets/icons/Vector.tsx
  src/components/atoms/GiftFilter/index.tsx
  src/components/atoms/Input/BasicInput/index.tsx
  src/components/atoms/Input/ShortInput/index.tsx
  src/components/friends/PresentRecommend.tsx
  src/components/friends/bottomsheet/PriceFilter.tsx
  src/components/friends/bottomsheet/SortItem.tsx
  src/pages/friends/index.tsx
  src/pages/onboarding/details/Agreement.tsx
  src/pages/onboarding/details/selectInfo/SelectFavor.tsx
  src/pages/onboarding/details/signup/Birth.tsx
  src/pages/onboarding/details/signup/Gender.tsx
  src/pages/settingPage/Account.tsx
  src/pages/settingPage/CustomerCenter.tsx
  src/pages/settingPage/Info.tsx
  src/pages/settingPage/NoticeDetail.tsx
  src/pages/settingPage/WriteForCustomer.tsx
  src/styles/theme/typo.ts
  src/utils/apis/friends/FriendsApi.tsx
  yarn.lock
Labels: Feature

#147 [Bug] 스토리북 빌드 에러 해결
  .github/workflows/storybook-deploy.yml
  .storybook/preview.tsx
  src/assets/icons/FilterIcon.tsx
  src/components/atoms/Category/Category.stories.tsx
  src/pages/settingPage/WriteForCustomer.tsx
  src/utils/apis/friends/FriendsApi.tsx
Labels: Bug

#155 feat: 3D 에셋 적용 및 애니메이션 적용
  .pnp.cjs
  .yarn/cache/@babel-runtime-npm-7.23.2-d013d6cf7e-6c4df4839e.zip
  .yarn/cache/@react-dnd-asap-npm-5.0.2-66021d3d61-18f040e535.zip
  .yarn/cache/@react-dnd-invariant-npm-4.0.2-826eacc1ea-594f6d7889.zip
  .yarn/cache/@react-dnd-shallowequal-npm-4.0.2-f944714335-7f21d691bd.zip
  .yarn/cache/dnd-core-npm-16.0.1-552224cee0-b7d3ef4664.zip
  .yarn/cache/react-dnd-html5-backend-npm-16.0.1-754940d855-e2368bf85d.zip
  .yarn/cache/react-dnd-npm-16.0.1-974f047d7b-e8da2186aa.zip
  .yarn/cache/redux-npm-4.2.1-e7e2cf2e37-f63b9060c3.zip
  package.json
  public/images/drink.png
  public/images/drum.png
  public/images/food.png
  public/images/music1.png
  public/images/my.png
  public/images/relation.png
  src/assets/icons/FriendList.tsx
  src/assets/icons/FriendsMenuIcon.tsx
  src/components/WeeklyQuestion/AnswerList.tsx
  src/components/WeeklyQuestion/DailyQuestionBox.tsx
  src/components/WeeklyQuestion/DragDropFriend.tsx
  src/components/WeeklyQuestion/QuestionImg.tsx
  src/components/atoms/AppBar/AppBar.stories.tsx
  src/components/atoms/AppBar/index.tsx
  src/components/atoms/Loading.tsx
  src/components/atoms/SquareButton/index.tsx
  src/components/auth/RequireAuth.tsx
  src/components/funnel/OneAnswerStep.tsx
  src/libs/hooks/useAuthMutate.ts
  src/libs/hooks/useInfiniteQueries.tsx
  src/libs/hooks/usehandleVisualViewport.ts
  src/libs/store/onboard.ts
  src/libs/store/question.ts
  src/pages/home/Redirect.tsx
  src/pages/onboarding/Onboarding.tsx
  src/pages/onboarding/details/selectInfo/SelectFavor.tsx
  src/pages/onboarding/details/signup/Birth.tsx
  src/pages/onboarding/details/signup/Gender.tsx
  src/pages/searchTaste/HCCUP.tsx
  src/pages/searchTaste/HCDIS.tsx
  src/pages/weekly/AnswerDailyQuestion.tsx
  src/pages/weekly/CheckAllAnswers.tsx
  src/pages/weekly/EditFriendList.tsx
  src/pages/weekly/WeeklyMainQuestion.tsx
  src/pages/weekly/index.tsx
  src/utils/apis/auth/AuthApi.ts
  src/utils/apis/friends/FriendsApi.tsx
  src/utils/apis/user/UserType.ts
  src/utils/apis/weekly/questionType.ts
  yarn.lock
Labels: Feature

#159 [chore] : legacy lottie 버전 제거
  .eslintrc.cjs
  .pnp.cjs
  .yarn/cache/@lottiefiles-react-lottie-player-npm-3.5.3-1b99195f06-083521730d.zip
  .yarn/cache/@types-react-lottie-npm-1.2.8-2d5b35a348-06f0fc53d4.zip
  .yarn/cache/babel-runtime-npm-6.26.0-d38e7946b4-8aeade9466.zip
  .yarn/cache/core-js-npm-2.6.12-0b93d77d31-44fa9934a8.zip
  .yarn/cache/react-lottie-npm-1.2.3-3d4f0a3852-05326e40b4.zip
  .yarn/cache/regenerator-runtime-npm-0.11.1-a31e4f8dcd-3c97bd2c7b.zip
  dockerfile
  package.json
  src/components/atoms/BottomSheet/index.tsx
  src/components/atoms/DayWeek/Day/Day.stories.tsx
  src/components/atoms/DayWeek/WeekGroup/Week/Week.stories.tsx
  src/components/atoms/DayWeek/WeekGroup/WeekGroup.stories.tsx
  src/components/atoms/Loading.tsx
  src/components/atoms/Text/text.stories.ts
  src/libs/hooks/useInfiniteQueries.tsx
  src/libs/hooks/usehandleVisualViewport.ts
  src/pages/onboarding/details/signup/Birth.tsx
  src/pages/onboarding/details/signup/Name.tsx
  src/pages/onboarding/details/signup/UserId.tsx
  src/pages/settingPage/WriteForCustomer.tsx
  src/utils/cookies.ts
  yarn.lock
Labels: Bug

#173 [Performance] : 퍼널 컴포넌트 다음 스텝시 reload 이슈 해결
  .pnp.cjs
  .yarn/cache/@emotion-is-prop-valid-npm-0.8.8-261a0f2426-bb7ec6d48c.zip
  .yarn/cache/@emotion-memoize-npm-0.7.4-5648cf11b8-4e3920d4ec.zip
  .yarn/cache/clsx-npm-1.2.1-77792dc182-30befca801.zip
  .yarn/cache/framer-motion-npm-10.16.5-7b95c1a890-189e26745c.zip
  .yarn/cache/react-toastify-npm-9.1.3-2f82dd0b41-e8bd92c5cb.zip
  package.json
  src/assets/icons/FilterIcon.tsx
  src/assets/image/modalGiftBox.png
  src/assets/image/onBoardingGreeting.png
  src/components/atoms/BottomSheet/index.tsx
  src/components/atoms/Modal/FullModal/index.tsx
  src/components/atoms/SnackBar/index.tsx
  src/components/atoms/SquareButton/index.tsx
  src/components/auth/CheckUserAuth.tsx
  src/components/auth/RequireAuth.tsx
  src/components/funnel/Funnel.tsx
  src/components/funnel/MultiAnswerStep.tsx
  src/components/funnel/OneAnswerStep.tsx
  src/components/funnel/SearchAnswerStep.tsx
  src/components/layouts/Dimmer.tsx
  src/components/layouts/Layout.tsx
  src/components/onboarding/GreetingOnboarding.tsx
  src/libs/hooks/useFunnel.tsx
  src/libs/hooks/useSnackBar.tsx
  src/libs/hooks/useStepNumberIcon.tsx
  src/libs/hooks/usehandleVisualViewport.ts
  src/libs/store/question.ts
  src/pages/profile/index.tsx
  src/pages/searchTaste/BMLIP.tsx
  src/pages/settingPage/LogOutBtn.tsx
  src/pages/weekly/WeeklyMainQuestion.tsx
  src/utils/apis/favor/FavorApi.ts
  vite.config.ts
  yarn.lock
Labels: Feature, Performance

#175 [Refac]: Funnel 명세 수정 반영
  src/assets/image/OnBoardGift.tsx
  src/assets/image/onBoardingImg.png
  src/components/atoms/SnackBar/index.tsx
  src/components/atoms/Tag/index.tsx
  src/components/friends/CopyMyIdButton.tsx
  src/components/funnel/MultiAnswerStep.tsx
  src/components/funnel/OneAnswerStep.tsx
  src/components/funnel/SearchAnswerStep.tsx
  src/components/layouts/Layout.tsx
  src/components/profile/NewTasteCategoryListItem.tsx
  src/components/profile/UserTagDataListItem.tsx
  src/libs/hooks/useFriendMutate.ts
  src/libs/hooks/useProfileMutate.tsx
  src/libs/store/dummy.ts
  src/libs/store/snackBar.ts
  src/pages/onboarding/details/HalfSuccess.tsx
  src/pages/profile/Profile.tsx
  src/pages/profile/index.tsx
  src/pages/searchTaste/BFMOI.tsx
  src/pages/searchTaste/BFPER.tsx
  src/pages/searchTaste/BFPLA.tsx
  src/pages/searchTaste/BMEYE.tsx
  src/pages/searchTaste/BMLIP.tsx
  src/pages/searchTaste/FAACC.tsx
  src/pages/searchTaste/FCTOP.tsx
  src/pages/searchTaste/FEBAG.tsx
  src/pages/searchTaste/FEDIG.tsx
  src/pages/searchTaste/FEFAS.tsx
  src/pages/searchTaste/HCCUP.tsx
  src/pages/searchTaste/HCDIS.tsx
  src/pages/settingPage/LogOutBtn.tsx
  src/utils/apis/favor/TasteType.ts
  src/utils/apis/user/UserApi.ts
  src/utils/parseTotasteQuestion.ts
Labels: Refactor
