Repository Team-TIFY/TIFY-CLIENT, pull requests merged in 2023-09, with the labels that each got.

#81 [Feature]: 데일리 질문- 답변 무한 스크롤 구현
  .pnp.cjs
  .yarn/cache/react-intersection-observer-npm-9.5.2-2c006290a0-cdbe405449.zip
  package.json
  src/App.tsx
  src/components/WeeklyQuestion/AnswerList.tsx
  src/components/WeeklyQuestion/CheckTodayDate.tsx
  src/components/WeeklyQuestion/DailyQuestionBox.tsx
  src/components/atoms/DayWeek/WeekGroup/Week/index.tsx
  src/components/atoms/RoundButton/RoundButton.stories.ts
  src/components/atoms/RoundButton/index.tsx
  src/libs/hooks/index.ts
  src/libs/hooks/useInfiniteQueries.tsx
  src/libs/types/questionType.ts
  src/main.tsx
  src/pages/weekly/AnswerDailyQuestion.tsx
  src/pages/weekly/CheckAllAnswers.tsx
  src/pages/weekly/WeeklyMainQuestion.tsx
  src/pages/weekly/index.tsx
  src/styles/theme/global.ts
  src/utils/apis/axios.ts
  src/utils/apis/weekly/WeeklyApi.ts
  tsconfig.json
  yarn.lock
Labels: Feature

#80 [UI]: Tag 컴포넌트 이미지 추가
  public/images/clothes.png
  public/images/cooking.png
  public/images/culturalLife.png
  public/images/exercise.png
  public/images/fashionStuff.png
  public/images/fragrance.png
  public/images/makeup.png
  public/images/travel.png
  src/assets/icons/Alert.tsx
  src/assets/icons/BigDownChevron.tsx
  src/assets/icons/BigLeftChevron.tsx
  src/assets/icons/BigPlus.tsx
  src/assets/icons/BigRightChevron.tsx
  src/assets/icons/BigUpChevron.tsx
  src/assets/icons/BigX.tsx
  src/assets/icons/Cherry.tsx
  src/assets/icons/CloseEye.tsx
  src/assets/icons/DayAfterLeftDown.tsx
  src/assets/icons/DayAfterRightUp.tsx
  src/assets/icons/DayBeforeLeftDown.tsx
  src/assets/icons/DayBeforeRightUp.tsx
  src/assets/icons/DaySelectedLeftDown.tsx
  src/assets/icons/DaySelectedRightUp.tsx
  src/assets/icons/DownArrow.tsx
  src/assets/icons/DownChevrons.tsx
  src/assets/icons/Fall.tsx
  src/assets/icons/FilledHeart.tsx
  src/assets/icons/FilterIcon.tsx
  src/assets/icons/Flying.tsx
  src/assets/icons/LeftArrow.tsx
  src/assets/icons/LeftChevrons.tsx
  src/assets/icons/Menu.tsx
  src/assets/icons/OffAlert.tsx
  src/assets/icons/OnAlert.tsx
  src/assets/icons/OpenEye.tsx
  src/assets/icons/Ordering.tsx
  src/assets/icons/Poke.tsx
  src/assets/icons/RightArrow.tsx
  src/assets/icons/RightChevrons.tsx
  src/assets/icons/Rocket.tsx
  src/assets/icons/Share.tsx
  src/assets/icons/Siren.tsx
  src/assets/icons/SmallDownChevron.tsx
  src/assets/icons/SmallLeftChevron.tsx
  src/assets/icons/SmallPlus.tsx
  src/assets/icons/SmallRightChevron.tsx
  src/assets/icons/SmallUpChevron.tsx
  src/assets/icons/SmallX.tsx
  src/assets/icons/Spring.tsx
  src/assets/icons/Summer.tsx
  src/assets/icons/TagIcon.tsx
  src/assets/icons/ThreeDots.tsx
  src/assets/icons/TifyLogo.tsx
  src/assets/icons/UnfilledHeart.tsx
  src/assets/icons/UpArrow.tsx
  src/assets/icons/UpChevrons.tsx
  src/assets/icons/Winter.tsx
  src/components/atoms/Filter/index.tsx
  src/components/atoms/Tag/Tag.stories.ts
  src/components/atoms/Tag/index.tsx
Labels: UI

#82 [Refactor] : 무한 스크롤 페이지 넘김 로직 구현 및 TextBubble Profile 정보 불러오기 로직 구현
  src/assets/icons/NavigationFriends.tsx
  src/assets/icons/NavigationMy.tsx
  src/assets/icons/NavigationToday.tsx
  src/components/WeeklyQuestion/AnswerList.tsx
  src/components/atoms/Navigationbar/index.tsx
  src/components/atoms/TextBubble/index.tsx
  src/libs/hooks/useInfiniteQueries.tsx
  src/pages/weekly/AnswerDailyQuestion.tsx
  src/pages/weekly/CheckAllAnswers.tsx
  src/styles/theme/global.ts
  src/utils/apis/weekly/WeeklyApi.ts
Labels: Refactor
